### ISSUE TITLE
Handling regular expression containing '|' symbol

### ISSUE THREAD

**Issue by Glazy** [loeffel-io/ls-lint#25]
We are trying to match files with the following regular expression: `[a-z][a-zA-Z0-9]*(Resolver|Schema)(\.test)?` using the below config:

```yaml
ls:
  .js: camelCase
  .ts: camelCase

  app/Handler/**:
    .ts: regex:[a-z][a-zA-Z0-9]*(Resolver|Schema)(\.test)?
```

However, upon running the tool, we receive the following error: `rule Schema)(\.test)? not exists`.

Any pointers on escaping the pipe character so we can achieve this functionality? 🙏

**Comment by Glazy** [comment]
Just re-read the documentation and saw the following bullet: `Multiple rules supported by | - They are logicly OR combined`.

If anyone else experiences this issue, I used the following to get it working:

```yaml
.ts: regex:[a-z][a-zA-Z0-9]*Schema(\.test)? | regex:[a-z][a-zA-Z0-9]*Resolver(\.test)?
```

Maybe the documentation could be updated to contain an `|` example and a regex example 🤔 If I get some time soon then I will submit a PR.

**Comment by loeffel-io** [comment]
Already working on a full documentation ✌🏻

Will be available soon: https://ls-lint.org

**Comment by loeffel-io** [comment]
Reopened the issue in case of | breaking the regex pattern

**Comment by loeffel-io** [comment]
Documentation released @ [ls-lint.org](https://ls-lint.org) 

@pustovalov listed you at the contributions: https://ls-lint.org/1.x/prologue/contributions.html#contributors 
@Glazy used a part of your regex definitions as examples: https://ls-lint.org/1.x/configuration/the-rules.html#using-multiple-regex-rules

Thank you guys! 

Issue closed because the issue is now documented
