### ISSUE TITLE
Incorrect documentation reference to snake_case

### ISSUE THREAD

**Issue by barnett** [loeffel-io/ls-lint#28]
On this [page](https://ls-lint.org/1.x/configuration/the-basics.html#using-multiple-rules) the below example is shown:

```
ls:
    .js: kebab-case

    models:
        .js: PascalCase

    src/templates:
        .js: snake-case
```

Notice `snake-case`, it should have an `_` instead, thus if ya run the above one would get an error. 

Tried to find a place to PR the fix but was unable to find such a location, hope the issue will be helpful.

**Comment by loeffel-io** [comment]
Hey @barnett, 

thank you for your contribution! 

As mentioned at [contributions](https://ls-lint.org/1.x/prologue/contributions.html) there is a [docs](https://github.com/ls-lint/docs) repository for that

Would love to see a PR from you if you want to, otherwise i will fix this in a few hours 

Have a good day!

**Comment by barnett** [comment]
Ah missed that, will put up a PR later today. Thanks you 🙏

**Comment by loeffel-io** [comment]
Thank you @barnett 

Added as contributor https://github.com/ls-lint/docs/commit/da783013ff54e0c8d455841cc63e8b5576fb01b8
