### ISSUE TITLE
Configuration file should be named .ls-lint.yaml

### ISSUE THREAD

**Issue by batisteo** [loeffel-io/ls-lint#29]
The extension `.yaml` should be preferred over `.yml`, in a similar way we use `.html` instead of `.htm`.

**Comment by loeffel-io** [comment]
Hey @batisteo,

thank you for your contribution! 

I personally do prefer `yml` instead of `yaml` but i will take care about that in `v2` by `ls-lint -f .ls-lint.yaml`.

**Comment by batisteo** [comment]
Cool

From https://yaml.org/faq.html:

> **Is there an official extension for YAML files?**
> Please use ".yaml" when possible.

**Comment by lo-corp** [comment]
how about picking `c` as config file argument? `ls-lint -c .ls-lint.yaml` `ls-lint --config .ls-lint.yaml` and not `ls-lint -f .ls-lint.yaml`?

**Comment by yuhr** [comment]
Why not allow both by default? I mean, pick the one which is present at the current directory. If both exists, I think it should simply abort, because then ls-lint can't tell which one is actually intended by the user. I'm afraid of that linting is *accidentally* passing or failing by this kind of implicit preference.

**Comment by loeffel-io** [comment]
With `v2.x` this is provided by the `config` option: https://github.com/loeffel-io/ls-lint/releases/tag/v2.0.0-beta.0

Feel free to try it out
